service: dynamodb-crud-aws-sdk-v3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource:
            - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/studentData"

functions:
  create:
    handler: functions/create.handler
    events:
      - http:
          path: /create
          method: post
  get:
    handler: functions/get.handler
    events:
      - http:
          path: /get
          method: post
  query:
    handler: functions/query.handler
    events:
      - http:
          path: /query
          method: post
  scan:
    handler: functions/scan.handler
    events:
      - http:
          path: /scan
          method: post
  delete:
    handler: functions/delete.handler
    events:
      - http:
          path: /delete
          method: post
  update:
    handler: functions/update.handler
    events:
      - http:
          path: /update
          method: post
  batchWrite:
    handler: functions/batchWrite.handler
    events:
      - http:
          path: /batchWrite
          method: post
