service: dynamodb-crud-aws-sdk-v3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  create:
    handler: functions/create.handler
    events:
      - http:
          path: /create
          method: post
  get:
    handler: functions/get.handler
    events:
      - http:
          path: /get
          method: post
  query:
    handler: functions/query.handler
    events:
      - http:
          path: /query
          method: post
  scan:
    handler: functions/scan.handler
    events:
      - http:
          path: /scan
          method: post
