service: dynamodb-crud-aws-sdk-v3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  create:
    handler: functions/create.handler
    events:
      - http:
          path: /create
          method: post
